### ISSUE TITLE
Throws uninitialized constant error on Fluent 0.14+

### ISSUE THREAD

**Issue by warmfusion** [restorando/fluent-plugin-amqp#7]
Errors seen when running on Ruby 2.1.5 with the following fluent plugins installed

- fluent-plugin-amqp (0.8.2, 0.8.1)
- fluent-plugin-elasticsearch (1.6.0)
- fluent-plugin-forest (0.3.1)
- fluent-plugin-record-reformer (0.8.2)
- fluentd (0.14.2)

```
2016-08-22 16:25:48 +0000 [error]: unexpected error error="uninitialized constant Fluent::Input"
...
2016-08-22 16:29:45 +0000 [error]: unexpected error error="uninitialized constant Fluent::TextParser"
```

Underlying cause;

Fluent doesn't auto include `fluent/input` or `fluent/parser` anymore - so need to add to the input and output plugins.

**Comment by warmfusion** [comment]
I shall create a feature branch and fix accordingly.

**Comment by jbarreneche** [comment]
We are using an old version of fluentd that's probably why it doesn't work with a newer one.

I'll be glad to review and release any PR that fixes the issue :)

**Comment by warmfusion** [comment]
I'm terribly sorry - I appear to have raise a ticket in the wrong fluent-plugin-amqp project :(

I discovered the bug in the fluent-plugin-amqp found here; https://github.com/giraffi/fluent-plugin-amqp  which is the fluent-plugin-amqp rather than amqp2...

So confusing.

Sorry about that.
